import { Meta, StoryObj } from '@storybook/react';
import { TextField } from '../components/input/TextField';
declare const _default: Meta;
export default _default;
type Story = StoryObj<typeof TextField>;
export declare const Default: Story;
export declare const Disabled: Story;
export declare const Password: Story;
export declare const WithPlaceholder: Story;
export declare const UnmanagedDefaultValue: Story;
export declare const ManagedDefaultValue: Story;
