name: Test Components 🎉
permissions:
  contents: read
  pull-requests: write
  
# This workflow is triggered on pushes to the main branch and pull requests to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Define the matrix of Node.js versions to test against
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
